Extended GET / PUT / DELETE resources (applinks)
aservo/confapi-bitbucket-plugin pull request #16
Opened 2020-10-08 14:51 UTC by lehmannk

This commit implements confapi-commons 0.26 interface implementation
for the applinks resource. In order to comply with the commons interface
stubs were generated for the remaining resources as well. These will
be implemented in separate PRs.

2020-10-08 15:08 UTC, lehmannk commented
bitte code smells aufgrund leerer Methoden kurzsfristig ignorieren, impl kommt in Kürze mit separatem PR.

2020-10-09 07:01 UTC, pathob requested changes
Ich teste das gleich nachm Mittag nochmal mit dem .forEach {} und dem Debugging

2020-10-09 07:15 UTC, lehmannk commented on src/main/java/de/aservo/confapi/bitbucket/service/ApplicationLinkServiceImpl.java
> +                                      @ComponentImport ApplinkStatusService applinkStatusService) {
oh sorry, das kam automatisch durch IntelliJ, muss ich nochmal manuell nachziehen

2020-10-09 07:27 UTC, lehmannk commented on src/main/java/de/aservo/confapi/bitbucket/service/ApplicationLinkServiceImpl.java
> +        });
wir können auch hier wieder wenige Elemente erwarten deshalb spielt das kaum eine Rolle. aber ja, im Prinzip hast du ja Recht, die bessere Vorlage wäre linear. ich optimiere das nochmal

2020-10-09 07:34 UTC, lehmannk commented
das debuggen mit dem .foreach geht doch genauso gut? Du nimmst doch auch IntelliJ oder? Hintergrund war eher allgemeines Alignment zur lambda Notation. Wir können aber loops auch gerne "traditional" implementieren, wenn das vom handling für dich einfacher ist. Ist ja schnell gemacht ;-)

2020-10-09 07:52 UTC, pathob approved these changes

2020-10-09 07:52 UTC, merged