Extended GET / PUT / DELETE resources (directories)
aservo/confapi-bitbucket-plugin pull request #17
Opened 2020-10-09 09:31 UTC by lehmannk

This commit implements confapi-commons 0.26 interface implementation
for the directories resource.

2020-10-12 05:36 UTC, pathob requested changes
Hatte irgendwie - auch bei vergangennen PR's - gedacht, dass ich bei deinen Tests nicht mehr so genau hinschauen muss. Und mich wohl leider geirrt.

```
assertTrue(true)
```

Ernsthaft?

2020-10-12 11:05 UTC, lehmannk commented
Du sprichst damit wahrscheinlich die `delete` methods an, die mit `assertTrue("Delete Successful", true);` enden. Die Methoden liefern void, es soll hier lediglich der Geradeauslauf getestet werden. Leider erwartet sonarcube immer irgendeine Art von Assertion in den Tests, daher diese Konstruktion. Verbesserungsvorschläge?

2020-10-19 09:03 UTC, lehmannk commented
Ich habe die entsprechenden unit Tests umgebaut und `verify` anstatt `assertTrue(true)` eingesetzt. Bitte nochmal reviewen

2020-10-19 15:05 UTC, pathob approved these changes

2020-10-19 15:05 UTC, merged